### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by sangh** [grantrutherford/kodi-remote-osx-widget#1]
So, I was going to try and build this to screw with the keyboard layout a little bit, but the dashcode I tried to download from dev...apple.com doesn't work with Xcode 7.3.  Rather than downgrade Xcode (is that even possible?) I thought I may be missing something.

So, grantrutherford, how do you modify and build this project?

**Comment by grantrutherford** [comment]
Hi Sangh, It seems you have worked it out but essentially widgets are just named folders you can enter and edit the files inside. If you need any further help don't hesitate to ask.

**Comment by sangh** [comment]
I did, a bit.  The files in `Parts` are still a nightmare to edit, though.  They say they should be generated with dashcode, which I guess is no longer working, so then the answer is if I need to edit them I should format them and edit by hand.  Alright, thanks!
